# -*- coding: utf-8 -*-
"""linear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18wk3f1VOZv39aUtXewdjKKbmPM3AcrQ9
"""

pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

# fetch dataset
df = fetch_ucirepo(id=320)

# data (as pandas dataframes)
X = df.data.features
y = df.data.targets

# metadata
print(df.metadata)

# variable information
print(df.variables)

X.head(5)

X.info()

X.describe()

X.isnull().sum()

corr=X.corr
corr

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

x=['sex','traveltime','studytime','health','absences']
y=['age']

from sklearn.model_selection import train_test_split

# Select the actual features from the DataFrame X using the list of column names 'x'
X_features = X[x]
# Select the actual target variable from the DataFrame X using the list of column names 'y'
y_target = X[y]

# Now, X_features and y_target will have the same number of samples (rows)
x_train,x_test,y_train,y_test=train_test_split(X_features, y_target, train_size=0.7,test_size=0.3,random_state=100)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

from sklearn.preprocessing import LabelEncoder

lm=LinearRegression()

# Initialize LabelEncoder
le = LabelEncoder()

# Encode the 'sex' column in both x_train and x_test
x_train.loc[:, 'sex'] = le.fit_transform(x_train['sex'])
x_test.loc[:, 'sex'] = le.transform(x_test['sex'])

lm.fit(x_train,y_train)

lm.intercept_

PredefinedSplit=lm.predict(x_test)
PredefinedSplit

coeff=pd.DataFrame(lm.coef_.T,x_train.columns,columns=['Coefficient'])
coeff

predictions = lm.predict(x_test)

##metrices

from sklearn import metrics

import numpy as np
print('MAE:', metrics.mean_absolute_error(y_test, predictions))
print('MSE:', metrics.mean_squared_error(y_test, predictions))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, predictions)))

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize= (10,6))

sns.regplot(data=X, x='traveltime', y='age',
           scatter_kws={'alpha':0.6}, line_kws={'color':'Red'})

plt.title('Best Fit Line: Travel Time vs. Age')

plt.show()

sns.scatterplot(data=X, x='traveltime', y='age')
plt