# -*- coding: utf-8 -*-
"""logisticregressionheart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nSjeGeWhT66Znyis-sGg0rTeo0XSG9Zn
"""

pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

# fetch dataset
heart_disease = fetch_ucirepo(id=45)

# data (as pandas dataframes)
X = heart_disease.data.features
y = heart_disease.data.targets

# metadata
print(heart_disease.metadata)

# variable information
print(heart_disease.variables)

X_test_scaled = sc.transform(X_test)
predictions = lr.predict(X_test_scaled)
print(predictions)

X.head()

X.isnull().sum()

X['ca']=X['ca'].fillna(X['ca'].median())
print(X['ca'])

X['thal']=X['thal'].fillna(X['thal'].median())
print(X['thal'])

X.isnull().sum()

X.duplicated().sum()

X=['sex','cp','fbs','restecg','exang','slope','ca','thal']
y=['age']

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
print(le)

from sklearn.model_selection import train_test_split
import pandas as pd # Ensure pandas is imported for DataFrame operations

# Re-establish X and y as the original dataframes/series from heart_disease object.
# These were overwritten by lists of strings in a previous cell.
# We assume 'heart_disease' object is still available in the kernel.
X = heart_disease.data.features.copy()
y = heart_disease.data.targets.copy()

# Re-apply the fillna operations that were done earlier in the notebook on 'ca' and 'thal'
X['ca'] = X['ca'].fillna(X['ca'].median())
X['thal'] = X['thal'].fillna(X['thal'].median())

# Now perform the train_test_split with the correctly defined X and y
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.4,random_state=44)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
print(lr)

lr

lr=LogisticRegression(max_iter=1000)
lr.fit(X_train,y_train)

predictions=lr.predict(X_test)
print(  predictions)

from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

import seaborn as sns
import matplotlib.pyplot as plt

predictions = lr.predict(X_test)
print(predictions)

accuracy = lr.score(X_test, y_test)
print(f"Accuracy: {accuracy}")

cm = confusion_matrix(y_test, predictions)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()